### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jkomg**
fixed some lists

### CODE REVIEW

**Comment by akeller** [comment]
LGTM!

**Review by scottdangelo — CHANGES_REQUESTED** [review]
Let's hold off on merging this. Amara is updating currently, and I believe some of this will already be changed by her PR.

**Comment by scottdangelo** [comment]
Oh, well it looks like it's OK ;)

**Comment by akeller** [comment]
I asked @jkomg to help me fix the number. He's a markdown expert.

**Comment by jkomg** [comment]
*expert* is a stretch but I'm happy I could help!

**Pull request merged**
